version = {{version}}

[eno3]
dhcp4 = true
dhcp6 = false

[eno2]
dhcp6 = true

[eno1]
dhcp4 = true

[eno4]
dhcp4 = false
dhcp6 = true

[eno5]
dhcp4 = true
dhcp6 = true

[eno6.dhcp4]
enabled = true
route-metric = 100

[eno6]
dhcp6 = false
