[services.docker]
restart-commands = ["/bin/systemctl try-restart docker.service"]
configuration-files = ["docker-daemon-config", "proxy-env"]

[configuration-files.docker-daemon-config]
path = "/etc/docker/daemon.json"
template-path = "/usr/share/templates/docker-daemon-json"

# Image registries. Retained for backwards compatibility, but superseded by the
# more specific metadata for mirrors and credentials.
[metadata.settings.container-registry]
affected-services = ["docker", "host-containers", "bootstrap-containers"]

# Image registry mirrors
[metadata.settings.container-registry.mirrors]
affected-services = ["docker", "host-containers", "bootstrap-containers"]

# Image registry credentials
[metadata.settings.container-registry.credentials]
affected-services = ["host-containers", "bootstrap-containers"]
