# Metrics
[settings.metrics]
send-metrics = false
service-checks = ["apiserver", "chronyd", "containerd", "host-containerd", "docker", "vmtoolsd"]

# Network
[metadata.settings.network]
affected-services = ["containerd", "docker", "host-containerd", "host-containers"]
