version = {{version}}

[bond1]
kind = "bond"
mode = "active-backup"
interfaces = ["eno53" , "eno54"]
dhcp4 = true

[bond1.monitoring]
arpmon-interval-ms = 0
arpmon-validate = "none"
arpmon-targets = []
