[package]
name = "public-admin-container-v0-9-0"
version = "0.1.0"
authors = ["Richard Kelly <rpkelly@amazon.com>"]
license = "Apache-2.0 OR MIT"
edition = "2018"
publish = false
# Don't rebuild crate just because of changes to README.
exclude = ["README.md"]

[dependencies]
migration-helpers = { path = "../../../migration-helpers", version = "0.1.0"}
