[package]
name = "libinih"
version = "0.1.0"
edition = "2021"
publish = false
build = "../build.rs"

[lib]
path = "../packages.rs"

[package.metadata.build-package]
releases-url = "https://github.com/benhoyt/inih/releases"

[[package.metadata.build-package.external-files]]
url = "https://github.com/benhoyt/inih/archive/refs/tags/r57.tar.gz"
path = "inih-r57.tar.gz"
sha512 = "9f758df876df54ed7e228fd82044f184eefbe47e806cd1e6d62e1b0ea28e2c08e67fa743042d73b4baef0b882480e6afe2e72878b175822eb2bdbb6d89c0e411"

[build-dependencies]
glibc = { path = "../glibc" }
