[package]
name = "open-vm-tools"
version = "0.1.0"
edition = "2021"
publish = false
build = "../build.rs"

[lib]
path = "../packages.rs"

[package.metadata.build-package]
releases-url = "https://github.com/vmware/open-vm-tools/releases/"

[[package.metadata.build-package.external-files]]
url = "https://github.com/vmware/open-vm-tools/releases/download/stable-12.2.5/open-vm-tools-12.2.5-21855600.tar.gz"
sha512 = "72db3b88f61624d26e8ff7e37e4fc52ecd0bec0b6f076d935870c03312321c5e0b406d05eae7012872734a50626ed760dff2cf872e26ec18ebf200aff5ed12ef"

[build-dependencies]
glibc = { path = "../glibc" }
libglib = { path = "../libglib" }
libtirpc = { path = "../libtirpc" }
libxcrypt = { path = "../libxcrypt" }
