[package]
name = "xfsprogs"
version = "0.1.0"
edition = "2021"
publish = false
build = "../build.rs"

[lib]
path = "../packages.rs"

[package.metadata.build-package]
releases-url = "https://mirrors.edge.kernel.org/pub/linux/utils/fs/xfs/xfsprogs/"

[[package.metadata.build-package.external-files]]
url = "http://kernel.org/pub/linux/utils/fs/xfs/xfsprogs/xfsprogs-6.4.0.tar.xz"
sha512 = "831e7747640bc2964b182226d8bb6f637610b123aeec9b3cb97a5de5d5b65bde30c6b40ad2e78de6a5214e823dd75de3a2bdfddd8ab1638f5c7340a760c91b3f"

[build-dependencies]
glibc = { path = "../glibc" }
libinih = { path = "../libinih" }
liburcu = { path = "../liburcu" }
util-linux = { path = "../util-linux" }

# RPM Requires
[dependencies]
# none
