version = 2
root = "/var/lib/host-containerd"
state = "/run/host-containerd"
disabled_plugins = [
    "io.containerd.internal.v1.opt",
    "io.containerd.snapshotter.v1.aufs",
    "io.containerd.snapshotter.v1.devmapper",
    "io.containerd.snapshotter.v1.native",
    "io.containerd.snapshotter.v1.zfs",
    "io.containerd.grpc.v1.cri",
]

[grpc]
address = "/run/host-containerd/containerd.sock"
