[package]
name = "libdbus"
version = "0.1.0"
edition = "2021"
publish = false
build = "../build.rs"

[lib]
path = "../packages.rs"

[package.metadata.build-package]
releases-url = "https://dbus.freedesktop.org/releases/dbus"

[[package.metadata.build-package.external-files]]
url = "https://dbus.freedesktop.org/releases/dbus/dbus-1.15.6.tar.xz"
sha512 = "8c2e207d98245d5f8d358e9824be9e8646af8147958e8bd56e18d478e8976e58a6645ee1aba62451fcc58443157e2a39c4a6ed9c2e440e7b6b05053d022f0113"

[build-dependencies]
glibc = { path = "../glibc" }
libcap = { path = "../libcap" }
libexpat = { path = "../libexpat" }
