[package]
name = "libz"
version = "0.1.0"
edition = "2021"
publish = false
build = "../build.rs"

[lib]
path = "../packages.rs"

[package.metadata.build-package]
releases-url = "https://www.zlib.net"

[[package.metadata.build-package.external-files]]
url = "https://www.zlib.net/zlib-1.3.tar.xz"
sha512 = "3868ac4da5842dd36c9dad794930675b9082ce15cbd099ddb79c0f6bd20a24aa8f33a123f378f26fe0ae02d91f31f2994dccaac565cedeaffed7b315e6ded2a2"

[build-dependencies]
glibc = { path = "../glibc" }
