[package]
name = "pigz"
version = "0.1.0"
edition = "2021"
publish = false
build = "../build.rs"

[lib]
path = "../packages.rs"

[[package.metadata.build-package.external-files]]
url = "https://zlib.net/pigz/pigz-2.8.tar.gz"
sha512 = "ae3d9d593e1645d65f9ab77aa828600c9af4bb30d0a073da7ae3dd805e65b87efaf6a0efb980f2d0168e475ae506eba194547d6479956dabb9d88293a9078a7f"

# RPM BuildRequires
[build-dependencies]
glibc = { path = "../glibc" }
libz = { path = "../libz" }

# RPM Requires
[dependencies]
# None
