[package]
name = "vmware-host-containers"
version = "0.1.0"
authors = ["Erikson Tung <etung@amazon.com>"]
license = "Apache-2.0 OR MIT"
edition = "2021"
publish = false
# Don't rebuild crate just because of changes to README.
exclude = ["README.md"]

[dependencies]
serde_json = "1"
migration-helpers = { path = "../../../migration-helpers", version = "0.1.0"}
