[package]
name = "pivot-repo-2020-07-07"
version = "0.1.0"
authors = ["Jamie Anderson <jamieand@amazon.com"]
license = "Apache-2.0 OR MIT"
edition = "2018"
publish = false
# Don't rebuild crate just because of changes to README.
exclude = ["README.md"]

[dependencies]
migration-helpers = { path = "../../../migration-helpers" }
