[package]
name = "libnftnl"
version = "0.1.0"
edition = "2021"
publish = false
build = "../build.rs"

[lib]
path = "../packages.rs"

[package.metadata.build-package]
releases-url = "https://netfilter.org/projects/libnftnl/files"

[[package.metadata.build-package.external-files]]
url = "http://netfilter.org/projects/libnftnl/files/libnftnl-1.2.6.tar.xz"
sha512 = "0c8c369eec84b0c568f0067598bece6e3be9a0fbd977e443ae3b14a5a6d842a6086ceb5426a65f8c77204709655f148c1241193f1a928f8c12154a57e3548b34"

[build-dependencies]
glibc = { path = "../glibc" }
libmnl = { path = "../libmnl" }
