[package]
name = "add-enable-spot-instance-draining"
version = "0.1.0"
authors = ["Magnus Kulke <mkulke@gmail.com>"]
license = "Apache-2.0 OR MIT"
edition = "2018"
publish = false
# Don't rebuild crate just because of changes to README.
exclude = ["README.md"]

[dependencies]
migration-helpers = { path = "../../../migration-helpers" }
