name: Build
on:
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

env:
  # When Go packages are built, buildsys will vendor in dependent Go code for
  # that package and bundle it up in a tarball. This env variable is consumed
  # and used to configure Go to directly download code from its upstream source.
  # This is a useful early signal during GitHub actions to see if there are
  # upstream Go code problems.
  GOPROXY: direct

jobs:
  list-variants:
    # This needs to be its own job since the build job needs its output before
    # it can initialize
    name: "Determine variants"
    runs-on: ubuntu-latest
    outputs:
      variants: ${{ steps.get-variants.outputs.variants }}
      aarch-enemies: ${{ steps.get-variants.outputs.aarch-enemies }}
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/list-variants
        id: get-variants
        with:
          filter-variants: true
          token: ${{ secrets.GITHUB_TOKEN }}

  build:
    needs: list-variants
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix:
        variant: ${{ fromJson(needs.list-variants.outputs.variants) }}
        arch: [x86_64, aarch64]
        exclude: ${{ fromJson(needs.list-variants.outputs.aarch-enemies) }}
      fail-fast: false
    name: ${{ matrix.variant }}-${{ matrix.arch }}
    steps:
      - uses: actions/checkout@v3
      - run: ./Makefile.sh ${{ matrix.variant }}
